#!/usr/bin/env bash
#MISE description="Build the CLI"
#USAGE arg "<configuration>" {
#USAGE   choices "debug" "release"
#USAGE   default "debug"
#USAGE }

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.bash" || exit 1

declare -a xcbeautify_args=("--disable-logging")
if [[ "${GITHUB_ACTIONS:-}" == "true" ]]; then
	xcbeautify_args+=("--renderer" "github-actions")
fi
readonly xcbeautify_args

mkdir -p "${ARTIFACTS_DIR}"
swift build --configuration "${usage_configuration?}" \
	| tee "${ARTIFACTS_DIR}/swift-build-$(now_utc).log" \
	| xcbeautify "${xcbeautify_args[@]}"
