#!/usr/bin/env bash
#MISE description="Build the CLI"
#USAGE arg "<configuration>" {
#USAGE   choices "debug" "release"
#USAGE   default "debug"
#USAGE }

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.bash" || exit 1

mkdir -p "${BUILD_DIR}/artifacts/logs"
swift build --configuration "${usage_configuration?}" \
	| tee "${BUILD_DIR}/artifacts/logs/build-$(now_utc).log"
